name = "langkawi-tour-api"
main = "worker.js"
compatibility_date = "2024-09-01"

[vars]
# Optional override for return URL
# SITE_URL = "https://langkawitravelntour.com"

# Set your Stripe Secret Key securely using:
# npx wrangler secret put STRIPE_SECRET_KEY
